.TH CHRONYC 8 
.\" NAME should be all caps, SECTION should be 1-8, maybe w/ subsection
.\" other parms are allowed: see man(7), man(1)
.SH NAME
chronyc \- controls the chronyd time daemon. 
.SH SYNOPSIS
.B chronyc
.I "[options] [files] ..."
.SH "DESCRIPTION"
.B chronyc
 This is a command-line driven control and monitoring
program.  An administrator can use this to fine-tune various
parameters within the daemon, add or delete servers etc whilst the
daemon is running.
.SH FILES
/etc/chrony/chrony.conf, /etc/chrony/chrony.keys, /var/lib/chrony/chrony.drift,
/etc/init.d/chrony, /etc/ppp/ip-up.d/chrony, /etc/ppp/ip-down.d/chrony,
/etc/cron.weekly/chrony, /var/log/chrony/
.SH "SEE ALSO"
The programs are documented fully in the info system under
.B chrony.
Just type 'info chrony'.  Also look at the files in /usr/share/doc/chrony.
.
.SH AUTHOR
This manual page was written by  John Hasler <john@dhh.gt.org> on Nov 7 1998,
based on Richard Curnow's info documents. 
It is licensed under the chrony license: see /usr/share/doc/chrony/COPYING.
