#!/bin/sh
# This script tells chronyd that the connection is down
# so that it won't try to contact the server. 
# John Hasler <jhasler@debian.org> 1 Dec. 1998

PASSWORD=`awk '$1 ~ /^1$/ {print $2; exit}' /etc/chrony/chrony.keys`
cat << EOF | /usr/bin/chronyc
password $PASSWORD
offline
EOF
exit 0
