#!/bin/sh
set -e
# postrm for chrony John Hasler Dec 17 1998
rm -f /var/lib/chrony/*
install-info --quiet --remove chrony.info
if [ -x /usr/bin/update-menus ] ; then 
	/usr/bin/update-menus
fi
if [ "$1" = "purge" ] ; then
	rm -rf /var/lib/chrony
	rm -rf /var/log/chrony
	rm -rf /etc/cron.weekly/chrony
	rm -rf /etc/ppp/ip-up.d/chrony
	rm -rf /etc/ppp/ip-down.d/chrony
	rm -rf /etc/chrony
	update-rc.d chrony remove >/dev/null
fi
