#!/bin/sh
set -e
#DEBHELPER#
# Automatically added by dh_installinit
install-info --quiet --remove /usr/share/info/chrony.info
/etc/init.d/chrony stop
if [ \( "$1" = "upgrade" -o "$1" = "remove" \) -a -L /usr/doc/pkg ]; then
     rm -f /usr/doc/pkg
fi
# End automatically added section
